### ISSUE TITLE
Where is StyleGuide in Solution

### ISSUE THREAD

**Issue by lsaudon** [sthewissen/FocusOnXamarin#1]
Hi, I watched the live Focus on Xamarin.
I can't find the breakdown you propose in your project.
![Capture](https://user-images.githubusercontent.com/25029876/77419700-1f58f880-6dc9-11ea-8b3d-f2ef8844d9a4.JPG)

**Comment by sthewissen** [comment]
Heya, thanks for watching! Yeah, that breakdown is not in there for demo purposes because I wanted to list the styles together to keep it clean. Here's a sample that uses that breakdown:

https://github.com/AppCreativity/BirdAtlas/blob/master/frontend/BirdAtlas/App.xaml
